.TH WSH 1
.SH NAME
wsh \- Withertech SHell
.SH SYNOPSIS
.B wsh
.SH DESCRIPTION
***WELCOME TO Withertech SHell HELP***
.br
Copyright @ WitherTech
.br
-Use the shell at your own risk...
.br
List of Commands supported:
.br
>cd
.br
>ls
.br
>exit
.br
>all other general commands available in UNIX shell
.br
>pipe handling
.br
>improper space handling
